/**
* Ocarina API
* OptiCAl Recognition of IdeNtity pApers
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package fr.cashbee.ocarina.client.models


import com.squareup.moshi.Json
/**
 * 
 * @param url 
 * @param uuid 
 */
data class DirectUploadResponse (
    @Json(name = "url")
    val url: java.net.URI? = null,
    @Json(name = "uuid")
    val uuid: java.util.UUID? = null
) {

}

