/**
* Ocarina API
* OptiCAl Recognition of IdeNtity pApers
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package fr.cashbee.ocarina.client.models

import fr.cashbee.ocarina.client.models.DocumentIdentificationInfoMetadata

import com.squareup.moshi.Json
/**
 * 
 * @param uuid 
 * @param status 
 * @param score 
 * @param metadata 
 */
data class DocumentIdentificationInfo (
    @Json(name = "uuid")
    val uuid: java.util.UUID? = null,
    @Json(name = "status")
    val status: DocumentIdentificationInfo.Status? = null,
    @Json(name = "score")
    val score: kotlin.Double? = null,
    @Json(name = "metadata")
    val metadata: DocumentIdentificationInfoMetadata? = null
) {

    /**
    * 
    * Values: pending,processing,validated,rejected,failed
    */
    enum class Status(val value: kotlin.String){
    
        @Json(name = "pending")
        pending("pending"),
    
        @Json(name = "processing")
        processing("processing"),
    
        @Json(name = "validated")
        validated("validated"),
    
        @Json(name = "rejected")
        rejected("rejected"),
    
        @Json(name = "failed")
        failed("failed");
    
    }

}

