/**
* Ocarina API
* OptiCAl Recognition of IdeNtity pApers
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package fr.cashbee.ocarina.client.models


import com.squareup.moshi.Json
/**
 * 
 * @param uuid UUID from direct upload request (optional)
 * @param filename 
 * @param contentType 
 */
data class DocumentsIdentificationRequest (
    /* UUID from direct upload request (optional) */
    @Json(name = "uuid")
    val uuid: java.util.UUID? = null,
    @Json(name = "filename")
    val filename: kotlin.String? = null,
    @Json(name = "content_type")
    val contentType: kotlin.String? = null
) {

}

