/**
* Ocarina API
* OptiCAl Recognition of IdeNtity pApers
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package fr.cashbee.ocarina.client.models


import com.squareup.moshi.Json
/**
 * 
 * @param idType 
 * @param firstName 
 * @param middleNames 
 * @param lastName 
 * @param birthDate 
 * @param birthPlace 
 * @param height 
 * @param serialNumber 
 * @param gender 
 * @param eyesColor Optional if id_type is not a passport
 * @param address 
 * @param deliveredBy 
 * @param deliveredDate 
 * @param validUntil 
 */
data class DocumentIdentificationInfoMetadata (
    @Json(name = "id_type")
    val idType: DocumentIdentificationInfoMetadata.IdType? = null,
    @Json(name = "first_name")
    val firstName: kotlin.String? = null,
    @Json(name = "middle_names")
    val middleNames: kotlin.String? = null,
    @Json(name = "last_name")
    val lastName: kotlin.String? = null,
    @Json(name = "birth_date")
    val birthDate: java.time.LocalDate? = null,
    @Json(name = "birth_place")
    val birthPlace: kotlin.String? = null,
    @Json(name = "height")
    val height: kotlin.Int? = null,
    @Json(name = "serial_number")
    val serialNumber: kotlin.String? = null,
    @Json(name = "gender")
    val gender: kotlin.String? = null,
    /* Optional if id_type is not a passport */
    @Json(name = "eyes_color")
    val eyesColor: kotlin.String? = null,
    @Json(name = "address")
    val address: kotlin.String? = null,
    @Json(name = "delivered_by")
    val deliveredBy: kotlin.String? = null,
    @Json(name = "delivered_date")
    val deliveredDate: java.time.LocalDate? = null,
    @Json(name = "valid_until")
    val validUntil: java.time.LocalDate? = null
) {

    /**
    * 
    * Values: passport,idCard
    */
    enum class IdType(val value: kotlin.String){
    
        @Json(name = "passport")
        passport("passport"),
    
        @Json(name = "id_card")
        idCard("id_card");
    
    }

}

